# use `prefix + I` to install it first time
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# restore after restart
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'nv'
set -g @resurrect-dir '~/.tmux/resurrect'
# `prefix + "ctrl-s"` to save
# `prefix + "ctrl-r"` to restore

set -g @continuum-boot 'on'

bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."
set -sg escape-time 10

# color
set-option -sa terminal-overrides ",xterm*:Tc"

# new windows are same dir
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# vim direction
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind L last-window

# makes copy easier
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# toggle status bar
bind-key b set-option status

### status bar ###
# https://draculatheme.com/tmux
set -g @dracula-plugins "cpu-usage ram-usage"
set -g @dracula-refresh-rate 5
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-left-icon-padding 0

run '~/.tmux/plugins/tpm/tpm'

