bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

set -g pane-active-border-style "fg=Turquoise4"
set -g status-style "bg=Turquoise4"

set -g status-right-length 100
# set status-right '%F %T'
set -g status-right '%F #(bash ~/dotfiles/time.sh)'

set -g window-status-format "#[fg=PaleTurquoise1]#I: #W"
set -g window-status-current-format "#[fg=lightgreen]#I: #W*"

set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'
