[pyprland]

plugins = [
  "scratchpads",
  "magnify",
  "shift_monitors",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "60% 60%"
